-- Migrasi 005: Membuat tabel jalur
CREATE TABLE IF NOT EXISTS jalur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_jalan VARCHAR(100) NOT NULL,
  lokasi VARCHAR(100) NOT NULL,
  arah VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);